Fix detect architectures to support gcc 14 (#892)
Update standard to c++17.  Seems to be an incompatibility between nvcc 12.9.86 and gcc 14.3.0 if we only use c++11.  The old compile line generated a bunch of errors in trying to compile `eval_gpu_archs.cu` causing local developer builds to fall back to building for all architectures.

With things set to c++11, the program `eval_gpu_archs.cu` fails to compile.  When that happens, the build scripts fall back to compiling for all architectures.  This fails for me with both libcugraph and libcudf.

Output from the compilation is:
```
nvcc warning : Support for offline compilation for architectures prior to '<compute/sm/lto>_75' will be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/type_traits(1610): error: "__is_nothrow_new_constructible" is not a function or static data member
      constexpr bool __is_nothrow_new_constructible
                     ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/type_traits(1610): error: "constexpr" is not valid here
      constexpr bool __is_nothrow_new_constructible
      ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/stl_pair.h(1190): error: "__is_pair" is not a function or static data member
      inline constexpr bool __is_pair = false;
                            ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/stl_pair.h(1190): error: "constexpr" is not valid here
      inline constexpr bool __is_pair = false;
             ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/stl_pair.h(1193): error: __is_pair is not a template
      inline constexpr bool __is_pair<pair<_Tp, _Up>> = true;
                            ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/stl_pair.h(1193): error: "constexpr" is not valid here
      inline constexpr bool __is_pair<pair<_Tp, _Up>> = true;
             ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/new_allocator.h(190): error: identifier "__is_nothrow_new_constructible" is undefined
   noexcept(__is_nothrow_new_constructible<_Up, _Args...>)
            ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/new_allocator.h(190): error: type name is not allowed
   noexcept(__is_nothrow_new_constructible<_Up, _Args...>)
                                           ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/new_allocator.h(190): error: expected a ")"
   noexcept(__is_nothrow_new_constructible<_Up, _Args...>)
                                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(107): error: variable template "std::__allocator_traits_base::__has_construct_impl" is not a valid class member template
        static constexpr bool __has_construct_impl = false;
                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(110): error: __has_construct_impl is not a template
        __has_construct_impl<_Alloc, _Tp,
        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(110): error: variable template "std::__allocator_traits_base::_Args" is not a valid class member template
        __has_construct_impl<_Alloc, _Tp,
        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(115): error: variable template "std::__allocator_traits_base::__has_construct" is not a valid class member template
        static constexpr bool __has_construct
                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: variable template "std::__allocator_traits_base::_Tp" is not a valid class member template
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                  ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: a constexpr static data member declaration requires an in-class initializer
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                     ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: expected an identifier
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: variable template "std::__allocator_traits_base::<error>" is not a valid class member template
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: a constexpr static data member declaration requires an in-class initializer
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                           ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: variable template "std::__allocator_traits_base::_Args" is not a valid class member template
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                             ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: a constexpr static data member declaration requires an in-class initializer
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                                  ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(116): error: expected a ";"
   = __has_construct_impl<_Alloc, _Tp, void, _Args...>;
                                                  ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(121): error: variable template "std::__allocator_traits_base::__has_new_expr" is not a valid class member template
        static constexpr bool __has_new_expr = false;
                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(124): error: __has_new_expr is not a template
        __has_new_expr<_Tp, __void_t<__new_expr_t<_Tp, _Args...>>, _Args...>
        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(124): error: variable template "std::__allocator_traits_base::_Args" is not a valid class member template
        __has_new_expr<_Tp, __void_t<__new_expr_t<_Tp, _Args...>>, _Args...>
        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(127): error: variable template "std::__allocator_traits_base::__can_construct" is not a valid class member template
        static constexpr bool __can_construct
                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(128): error: variable template "std::__allocator_traits_base::_Tp" is not a valid class member template
   = __has_construct<_Alloc, _Tp, _Args...>
                             ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(128): error: a constexpr static data member declaration requires an in-class initializer
   = __has_construct<_Alloc, _Tp, _Args...>
                                ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(128): error: variable template "std::__allocator_traits_base::_Args" is not a valid class member template
   = __has_construct<_Alloc, _Tp, _Args...>
                                  ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(128): error: a constexpr static data member declaration requires an in-class initializer
   = __has_construct<_Alloc, _Tp, _Args...>
                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(128): error: expected a ";"
   = __has_construct<_Alloc, _Tp, _Args...>
                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(377): error: identifier "__can_construct" is undefined
   __enable_if_t<__can_construct<_Alloc, _Tp, _Args...>>
                 ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(377): error: type name is not allowed
   __enable_if_t<__can_construct<_Alloc, _Tp, _Args...>>
                                 ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(377): error: too many arguments for alias template "std::__enable_if_t"
   __enable_if_t<__can_construct<_Alloc, _Tp, _Args...>>
                                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(377): error: expected an identifier
   __enable_if_t<__can_construct<_Alloc, _Tp, _Args...>>
                                                      ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: identifier "__has_construct" is undefined
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                 ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: type name is not allowed
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                                 ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: too many arguments for alias template "std::__enable_if_t"
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                                              ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: expected an identifier
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: variable template "std::allocator_traits<_Alloc>::<error>" is not a valid class member template
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: a constexpr static data member declaration requires an in-class initializer
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                       ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(439): error: expected an identifier
   __enable_if_t<__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                         ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(441): error: expected a ";"
   { return noexcept(__a->construct(__p, std::declval<_Args>()...)); }
   ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: identifier "__has_construct" is undefined
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                  ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: type name is not allowed
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                                  ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: too many arguments for alias template "std::__enable_if_t"
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                                               ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: expected an identifier
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: variable template "std::allocator_traits<_Alloc>::<error>" is not a valid class member template
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: a constexpr static data member declaration requires an in-class initializer
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                        ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(445): error: expected an identifier
   __enable_if_t<!__has_construct<_Alloc, _Tp, _Args...>, bool>
                                                          ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(447): error: expected a ";"
   { return __is_nothrow_new_constructible<_Tp, _Args...>; }
   ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(705): error: identifier "__is_nothrow_new_constructible" is undefined
   noexcept(__is_nothrow_new_constructible<_Up, _Args...>)
            ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(705): error: type name is not allowed
   noexcept(__is_nothrow_new_constructible<_Up, _Args...>)
                                           ^

/home/coder/.conda/envs/rapids/lib/gcc/x86_64-conda-linux-gnu/14.3.0/include/c++/bits/alloc_traits.h(705): error: expected a ")"
   noexcept(__is_nothrow_new_constructible<_Up, _Args...>)
                                              ^

53 errors detected in the compilation of "/home/coder/cugraph/cpp/build/eval_gpu_archs.cu".
```

Authors:
  - Chuck Hastings (https://github.com/ChuckHastings)
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/rapidsai/rapids-cmake/pull/892